version: '2'
services:
    codemotion-app:
        image: codemotion
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://codemotion-mysql:3306/codemotion?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    codemotion-mysql:
        extends:
            file: mysql.yml
            service: codemotion-mysql
